name: Repo diagram

on:
  push:
    branches: [ "main" ]   
jobs:
  visualize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate repo diagram (artifact only)
        uses: githubocto/repo-visualizer@0.7.1
        with:
          output_file: diagram.svg    
          artifact_name: diagram       
          should_push: false          
